/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author juand
 */
public class login extends javax.swing.JFrame {

    
    

    public login() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        contraseña_textfield = new javax.swing.JPasswordField();
        usuario_textfield = new javax.swing.JTextField();
        panel_ingresa = new javax.swing.JPanel();
        label_login = new javax.swing.JLabel();
        panel_registro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(420, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(452, 150));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contraseña_textfield.setForeground(new java.awt.Color(51, 153, 255));
        contraseña_textfield.setText("******");
        contraseña_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraseña_textfieldMouseClicked(evt);
            }
        });
        contraseña_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseña_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(contraseña_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 190, 30));

        usuario_textfield.setForeground(new java.awt.Color(51, 153, 255));
        usuario_textfield.setText("Usuario(CC)");
        usuario_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuario_textfieldMouseClicked(evt);
            }
        });
        usuario_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuario_textfieldKeyPressed(evt);
            }
        });
        getContentPane().add(usuario_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 190, 30));

        panel_ingresa.setBackground(new java.awt.Color(51, 153, 255));
        panel_ingresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_ingresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ingresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ingresaMouseExited(evt);
            }
        });
        panel_ingresa.setLayout(new java.awt.GridBagLayout());

        label_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setText("INGRESA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 30);
        panel_ingresa.add(label_login, gridBagConstraints);

        getContentPane().add(panel_ingresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, 25));

        panel_registro.setBackground(new java.awt.Color(51, 153, 255));
        panel_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_registroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_registroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_registroMouseExited(evt);
            }
        });
        panel_registro.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRATE");
        panel_registro.add(jLabel1, new java.awt.GridBagConstraints());

        getContentPane().add(panel_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 100, 25));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 450, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuario_textfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuario_textfieldMouseClicked
        usuario_textfield.setText("");
    }//GEN-LAST:event_usuario_textfieldMouseClicked

    private void contraseña_textfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseña_textfieldMouseClicked
        contraseña_textfield.setText("");

    }//GEN-LAST:event_contraseña_textfieldMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        usuario_textfield.setText("Usuario(CC)");
        contraseña_textfield.setText("******");
    }//GEN-LAST:event_formMouseClicked

    private void panel_registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_registroMouseEntered
        panel_registro.setBackground(new Color(50,173,255));
    }//GEN-LAST:event_panel_registroMouseEntered

    private void panel_ingresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ingresaMouseEntered
        panel_ingresa.setBackground(new Color(50,173,255));
    }//GEN-LAST:event_panel_ingresaMouseEntered

    private void panel_ingresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ingresaMouseExited
        panel_ingresa.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_panel_ingresaMouseExited

    private void panel_registroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_registroMouseExited
        panel_registro.setBackground(new Color(51, 153, 255));

    }//GEN-LAST:event_panel_registroMouseExited

    private void panel_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_registroMouseClicked
        registro Registro = new registro();
        Registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panel_registroMouseClicked

    private void contraseña_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseña_textfieldActionPerformed

    }//GEN-LAST:event_contraseña_textfieldActionPerformed

    private void usuario_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuario_textfieldKeyPressed

    }//GEN-LAST:event_usuario_textfieldKeyPressed

    private void panel_ingresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ingresaMouseClicked
        
        
    }//GEN-LAST:event_panel_ingresaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel label_login;
    private javax.swing.JPanel panel_ingresa;
    private javax.swing.JPanel panel_registro;
    private javax.swing.JTextField usuario_textfield;
    // End of variables declaration//GEN-END:variables
}
